-- Owned, synthetic PostgreSQL fixture; each test resets only its disposable database.
DROP TABLE IF EXISTS pg_item, pg_category CASCADE;
CREATE TABLE pg_category (id INTEGER PRIMARY KEY, label TEXT NOT NULL);
CREATE TABLE pg_item
(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   tenant INTEGER NOT NULL,
   name TEXT NOT NULL UNIQUE,
   category_id INTEGER REFERENCES pg_category(id),
   quantity BIGINT,
   amount NUMERIC(20,4),
   enabled BOOLEAN,
   day DATE,
   at_time TIME,
   at_instant TIMESTAMP,
   note TEXT,
   html TEXT,
   payload BYTEA
);
INSERT INTO pg_category VALUES (1,'Food'),(2,'Drink');
INSERT INTO pg_item(id,tenant,name,category_id,quantity,amount,enabled) VALUES
   (1,1,'Alpha',1,10,2.50,true),
   (2,1,'Beta',1,20,3.25,false),
   (3,2,'Gamma',2,30,5.00,true),
   (4,1,'Delta',NULL,NULL,NULL,NULL);
ALTER TABLE pg_item ALTER COLUMN id RESTART WITH 100;
