/*
 * QQQ - Low-code Application Framework for Engineers.
 * Copyright (C) 2021-2022.  Kingsrook, LLC
 * 651 N Broad St Ste 205 # 6917 | Middletown DE 19709 | United States
 * contact@kingsrook.com
 * https://github.com/Kingsrook/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.kingsrook.sampleapp;


import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.kingsrook.qqq.backend.core.actions.processes.RunProcessAction;
import com.kingsrook.qqq.backend.core.context.QContext;
import com.kingsrook.qqq.backend.core.exceptions.QException;
import com.kingsrook.qqq.backend.core.model.actions.processes.ProcessSummaryLine;
import com.kingsrook.qqq.backend.core.model.actions.processes.RunBackendStepInput;
import com.kingsrook.qqq.backend.core.model.actions.processes.RunBackendStepOutput;
import com.kingsrook.qqq.backend.core.model.actions.processes.RunProcessInput;
import com.kingsrook.qqq.backend.core.model.actions.processes.RunProcessOutput;
import com.kingsrook.qqq.backend.core.model.actions.tables.QInputSource;
import com.kingsrook.qqq.backend.core.model.actions.tables.query.QCriteriaOperator;
import com.kingsrook.qqq.backend.core.model.actions.tables.query.QFilterCriteria;
import com.kingsrook.qqq.backend.core.model.actions.tables.query.QQueryFilter;
import com.kingsrook.qqq.backend.core.model.data.QRecord;
import com.kingsrook.qqq.backend.core.model.metadata.QInstance;
import com.kingsrook.qqq.backend.core.model.metadata.fields.QFieldMetaData;
import com.kingsrook.qqq.backend.core.model.metadata.fields.QFieldType;
import com.kingsrook.qqq.backend.core.model.metadata.tables.QTableMetaData;
import com.kingsrook.qqq.backend.core.model.session.QSession;
import com.kingsrook.qqq.backend.core.model.session.QUser;
import com.kingsrook.qqq.backend.core.processes.implementations.etl.streamedwithfrontend.AbstractExtractStep;
import com.kingsrook.qqq.backend.core.processes.implementations.etl.streamedwithfrontend.ExtractViaQueryStep;
import com.kingsrook.qqq.backend.core.processes.implementations.tablesync.AbstractTableSyncTransformStep;
import com.kingsrook.qqq.backend.core.processes.implementations.tablesync.TableSyncProcess;
import com.kingsrook.qqq.backend.core.utils.Pair;
import com.kingsrook.qqq.backend.module.rdbms.jdbc.ConnectionManager;
import com.kingsrook.qqq.backend.module.rdbms.model.metadata.RDBMSTableBackendDetails;
import com.kingsrook.sampleapp.metadata.SampleMetaDataProvider;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;


/*******************************************************************************
 ** Person synchronization with a native destination and independent SQL readback.
 *******************************************************************************/
class SampleTableSyncTest
{
   private static final String TARGET = "samplePersonSync";



   /*******************************************************************************
    **
    *******************************************************************************/
   @BeforeEach
   void setUp() throws Exception
   {
      ConnectionManager.resetConnectionProviders();
      SampleMetaDataProvider.primeTestDatabase("prime-test-database.sql");
      sql("DROP TABLE IF EXISTS sample_person_sync");
      sql("CREATE TABLE sample_person_sync (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, personid INTEGER UNIQUE NOT NULL, firstname VARCHAR(100), lastname VARCHAR(100))");
      sql("INSERT INTO sample_person_sync (personid,firstname,lastname) SELECT id,CASE WHEN id=1 THEN 'Stale' ELSE first_name END,last_name FROM person WHERE id<=2");
      QInstance instance = SampleMetaDataProvider.defineTestInstance();
      instance.addTable(new QTableMetaData().withName(TARGET).withPrimaryKeyField("id")
         .withBackendName(SampleMetaDataProvider.RDBMS_BACKEND_NAME)
         .withBackendDetails(new RDBMSTableBackendDetails().withTableName("sample_person_sync"))
         .withField(new QFieldMetaData("id", QFieldType.INTEGER))
         .withField(new QFieldMetaData("personid", QFieldType.INTEGER))
         .withField(new QFieldMetaData("firstname", QFieldType.STRING))
         .withField(new QFieldMetaData("lastname", QFieldType.STRING)));
      instance.addProcess(TableSyncProcess.processMetaDataBuilder(false).withName("syncPeople").withTableName("person")
         .withSyncTransformStepClass(SyncPeople.class).withExtractStepClass(ExtractViaQueryStep.class).getProcessMetaData());
      instance.addProcess(TableSyncProcess.processMetaDataBuilder(false).withName("failedSync").withTableName("person")
         .withSyncTransformStepClass(SyncPeople.class).withExtractStepClass(FailingSource.class).getProcessMetaData());
      QContext.init(instance, new QSession().withUser(new QUser().withIdReference("owned-sync-user")).withPermissions());
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   @AfterEach
   void tearDown()
   {
      QContext.clear();
      ConnectionManager.resetConnectionProviders();
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   @Test
   void testInsertUpdateSkipAndRepeatedSync() throws Exception
   {
      RunProcessOutput output = new RunProcessAction().execute(input());
      List<?> summary = (List<?>) output.getValue("processResults");
      assertEquals(3, ((ProcessSummaryLine) summary.get(0)).getCount());
      assertEquals(1, ((ProcessSummaryLine) summary.get(1)).getCount());
      assertEquals(sourceRows(), rows());
      List<String> first = rows();
      RunProcessOutput repeated = new RunProcessAction().execute(input());
      assertEquals(first, rows());
      List<?> repeatedSummary = (List<?>) repeated.getValue("processResults");
      assertTrue(repeatedSummary.isEmpty());
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   @Test
   void testPreviewDoesNotPersistThenConfirmedLoadDoes() throws Exception
   {
      List<String> before = rows();
      RunProcessInput input = input();
      input.setFrontendStepBehavior(RunProcessInput.FrontendStepBehavior.BREAK);
      RunProcessOutput preview = new RunProcessAction().execute(input);
      assertEquals("review", preview.getProcessState().getNextStepName().orElseThrow());
      assertEquals(before, rows());
      input.setStartAfterStep("review");
      new RunProcessAction().execute(input);
      assertEquals(sourceRows(), rows());
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   @Test
   void testNoInsertAndNoUpdateOptions() throws Exception
   {
      RunProcessInput noInsert = input();
      noInsert.addValue("syncTablePerformInsertsKey", false);
      new RunProcessAction().execute(noInsert);
      assertEquals(sourceRows().subList(0, 2), rows());
      sql("UPDATE sample_person_sync SET firstname='Stale' WHERE personid=1");
      RunProcessInput noUpdate = input();
      noUpdate.addValue("syncTablePerformUpdatesKey", false);
      new RunProcessAction().execute(noUpdate);
      assertEquals(5, rows().size());
      assertTrue(rows().get(0).startsWith("1:Stale:"));
      assertEquals(sourceRows().subList(1, 5), rows().subList(1, 5));
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   @Test
   void testDuplicateMissingKeysMixedErrorsAndCustomFilter() throws Exception
   {
      List<String> before = rows();
      RunBackendStepInput input = new RunBackendStepInput();
      input.setProcessName("syncPeople");
      input.setTableName("person");
      input.setInputSource(QInputSource.USER);
      input.setRecords(List.of(person(3, "Casey"), person(3, "Duplicate"), person(null, "No key"), person(4, "Reject")));
      RunBackendStepOutput output = new RunBackendStepOutput();
      SyncPeople transform = new SyncPeople();
      transform.runOnePage(input, output);
      assertEquals(1, output.getRecords().size());
      assertEquals(3, output.getRecords().get(0).getValueInteger("personid"));
      assertEquals(1, ((ProcessSummaryLine) transform.getProcessSummary(output, true).get(1)).getCount());
      assertEquals(1, ((ProcessSummaryLine) transform.getProcessSummary(output, true).get(2)).getCount());
      assertEquals(before, rows());
      input.setRecords(List.of(person(2, "Changed")));
      input.addValue("maximumExistingKey", 1);
      RunBackendStepOutput filtered = new RunBackendStepOutput();
      new SyncPeople().runOnePage(input, filtered);
      assertNull(filtered.getRecords().get(0).getValue("id"));
      assertEquals(before, rows());
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   @Test
   void testSourceFailureDoesNotWrite() throws Exception
   {
      List<String> before = rows();
      RunProcessInput input = input();
      input.setProcessName("failedSync");
      assertThrows(QException.class, () -> new RunProcessAction().execute(input));
      assertEquals(before, rows());
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   private RunProcessInput input()
   {
      RunProcessInput input = new RunProcessInput();
      input.setProcessName("syncPeople");
      input.setInputSource(QInputSource.USER);
      input.addValue("recordIds", "1,2,3,4,5");
      input.setFrontendStepBehavior(RunProcessInput.FrontendStepBehavior.SKIP);
      return input;
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   private QRecord person(Integer id, String name)
   {
      return new QRecord().withValue("id", id).withValue("firstName", name);
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   private void sql(String sql) throws Exception
   {
      try(Connection connection = ConnectionManager.getConnection(SampleMetaDataProvider.defineRdbmsBackend()); Statement statement = connection.createStatement())
      {
         statement.execute(sql);
      }
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   private List<String> rows() throws Exception
   {
      return read("SELECT personid,firstname,lastname FROM sample_person_sync ORDER BY personid");
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   private List<String> sourceRows() throws Exception
   {
      return read("SELECT id,first_name,last_name FROM person ORDER BY id");
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   private List<String> read(String sql) throws Exception
   {
      List<String> rows = new ArrayList<>();
      try(Connection connection = ConnectionManager.getConnection(SampleMetaDataProvider.defineRdbmsBackend()); Statement statement = connection.createStatement(); ResultSet result = statement.executeQuery(sql))
      {
         while(result.next())
         {
            rows.add(result.getInt(1) + ":" + result.getString(2) + ":" + result.getString(3));
         }
      }
      return rows;
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   public static class SyncPeople extends AbstractTableSyncTransformStep
   {



      /*******************************************************************************
       **
       *******************************************************************************/
      @Override
      protected SyncProcessConfig getSyncProcessConfig()
      {
         return new SyncProcessConfig("person", "id", TARGET, "personid");
      }



      /*******************************************************************************
       **
       *******************************************************************************/
      @Override
      protected List<Pair<String, String>> getLookupsToPreLoad()
      {
         return List.of(new Pair<>("person", "id"));
      }



      /*******************************************************************************
       **
       *******************************************************************************/
      @Override
      protected QQueryFilter getExistingRecordQueryFilter(RunBackendStepInput input, List<Serializable> keys)
      {
         QQueryFilter filter = super.getExistingRecordQueryFilter(input, keys);
         if(input.getValueInteger("maximumExistingKey") != null)
         {
            filter.withCriteria(new QFilterCriteria("personid", QCriteriaOperator.LESS_THAN_OR_EQUALS, input.getValueInteger("maximumExistingKey")));
         }
         return filter;
      }



      /*******************************************************************************
       **
       *******************************************************************************/
      @Override
      public QRecord populateRecordToStore(RunBackendStepInput input, QRecord destination, QRecord source) throws QException
      {
         if("Reject".equals(source.getValueString("firstName")))
         {
            throw new QException("Owned invalid source record");
         }
         QRecord lookup = recordLookupHelper.getRecordByKey("person", "id", source.getValue("id"));
         if(Objects.equals(destination.getValue("firstname"), source.getValue("firstName"))
            && Objects.equals(destination.getValue("lastname"), lookup.getValue("lastName")))
         {
            return null;
         }
         return destination.withValue("personid", source.getValue("id"))
            .withValue("firstname", source.getValue("firstName")).withValue("lastname", lookup.getValue("lastName"));
      }
   }



   /*******************************************************************************
    **
    *******************************************************************************/
   public static class FailingSource extends AbstractExtractStep
   {



      /*******************************************************************************
       **
       *******************************************************************************/
      @Override
      public void run(RunBackendStepInput input, RunBackendStepOutput output) throws QException
      {
         throw new QException("Owned source unavailable before first page");
      }
   }
}
